# -*- ruby -*-

def update input, output
  sh "erb #{input} > #{output}"
end

task :default => ["index.html"]

file "index.html" => ["index.rhtml"] do |t|
  update t.prerequisites[0], t.name
end

task :index do
  update "index.rhtml", "index.html"
end
